### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JoaoGFarias** [miguelarauj1o/ackley#14]
The following issues are crucial to develop the algorithm and I have no idea of the answers:

1 - When to do recombination or mutation?
   - On the genetic algorithm, we have a probability of mutation on each interaction. What's the mechanism on evolutionary strategy?

2 - What's the population size?
   - The [wikipedia](https://en.wikipedia.org/wiki/Evolution_strategy#Methods) talks about (μ/ρ+, λ)-ES, but I don't know the actual values. Any idea?

3 - Co-related mutation
   - Does someone knows how it works?

cc: @miguelarauj1o and @pcstl

**Comment by JoaoGFarias** [comment]
2 - Is section 4.7 the answer?
I'm not sure, but I'm working with this on #17 
<img width="884" alt="screen shot 2016-05-23 at 9 20 58 pm" src="https://cloud.githubusercontent.com/assets/1585655/15488405/52aed012-212c-11e6-86c9-96b5b9616ffe.png">

**Comment by pcstl** [comment]
Re: whether to recombinate or mutate:

In (1, N) evolution strategies you should only worry about mutation. Since you have only a single parent, there is no way to actually recombinate anything. You should just apply mutation N times and choose the best of the N offspring to be the next parent.

In (P, Q) and (P + Q) strategies you should apply the following algorithm:

- Apply recombination among the offspring until you have Q candidate offspring
- Mutate each of the Q candidate offspring
- Choose the P best from the candidate offspring ((P, Q) selection) or from the union of candidate offspring and parents ((P + Q) selection)
- The P best become the next generation
